name: Build reference-apps CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-release:
    name: Build refapps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install TypeScript
        run: npm install -g typescript@5.3.2

      - name: Run Linter
        run: yarn lint

      - name: Install dependencies
        run: yarn install

      - name: Build reference apps
        run: yarn build:refapps
