name: Make a refapps release with compiled package archives

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    name: Build refapps and make a release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build reference apps
        run: yarn build:refapps

      - name: Create a release and upload artifacts
        run: |
          cd js;
          for pkg in *.tar.gz; do
            mv $pkg ../js-$pkg;
          done
          cd ..;
          cd python;
          for pkg in *.tar.gz; do
            mv $pkg ../py-$pkg;
          done
        env:
          GITHUB_TOKEN: ${{ secrets.SCRAMJET_BOT_TOKEN }}

      - name: Create a release and upload artifacts
        run: gh release create ${{ github.ref }} *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.SCRAMJET_BOT_TOKEN }}
