name: Make a refapps release with compiled package archives

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    name: Build refapps and make a release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build reference apps
        run: yarn build:refapps

      - name: Create a release and upload artifacts
        run: >
          gh release create ${{ github.ref }}
          js/*.tar.gz
          ts/*.tar.gz
          python/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.SCRAMJET_BOT_TOKEN }}
